Repository JunalChowdhuryG/Grupo-2-Practica-Calificada-4, pull requests merged in 2025-06, with the labels that each got.

#9 merge[#1]: Fusionar rama setup-estructura-repositorio a develop
  .flake8
  .gitignore
  README.md
  docs/.gitkeep
  pytest.ini
  reports/.gitkeep
  requirements.txt
  scripts/.gitkeep
  src/.gitkeep
  tests/.gitkeep
Labels: Sprint 1, Merge

#10 merge[#2]: fusionar rama feature-hook-commit-msg a develop
  hooks/commit-msg
Labels: Sprint 1, in_review, Bash

#26 merge[#17]: Fusionar rama feature-manifest-kubernetes a develop
  docs/workflows.yaml
  k8s/nginx-deployment.yaml
  src/k8s_deploy.py
Labels: Sprint 2, PR_Aprobado
